import type { Application } from './types';

export const SEED: Application[] = [
  {
    id: 'FL-A8K2X9', submittedAt: '2026-05-22T10:24:00Z', status: 'Lead', studyLevel: 'UG',
    fullName: 'Aanya Krishnan', email: 'aanya.k@example.com', phone: '+91 98450 12345',
    dob: '2007-08-14', city: 'Bangalore', state: 'Karnataka',
    tenthBoard: 'CBSE', tenthYear: '2023', tenthPct: '94%',
    tenthFile: { name: 'aanya_10th.pdf', size: 412000, type: 'application/pdf' },
    eleventhStream: 'Science (PCM)', eleventhSchool: 'DPS Bangalore',
    eleventhFile: { name: 'aanya_11th.pdf', size: 320000, type: 'application/pdf' },
    twelfthBoard: 'CBSE', twelfthYear: '2025', twelfthPct: '91%',
    twelfthFile: { name: 'aanya_12th.pdf', size: 380000, type: 'application/pdf' },
    ugFile: null,
    jeeScore: '98.4 percentile', neetScore: '', cetScore: '',
    preferredProgram: 'B.Tech', preferredCity: 'Bangalore',
    preferredUniversity: 'M. S. Ramaiah Institute of Technology',
    goals: 'I want to pursue computer science with a strong focus on AI/ML research. Looking for a campus with active research labs and industry connections.',
  },
  {
    id: 'FL-B3M7P1', submittedAt: '2026-05-22T08:11:00Z', status: 'Contacted', studyLevel: 'UG',
    fullName: 'Rohan Menon', email: 'rohan.menon@example.com', phone: '+91 95390 87654',
    dob: '2007-02-03', city: 'Kochi', state: 'Kerala',
    tenthBoard: 'ICSE', tenthYear: '2023', tenthPct: '89%',
    tenthFile: { name: 'rohan_10th.jpg', size: 1200000, type: 'image/jpeg' },
    eleventhStream: 'Science (PCM)', eleventhSchool: 'Bhavans Vidya Mandir',
    eleventhFile: null,
    twelfthBoard: 'ICSE / ISC', twelfthYear: '2025', twelfthPct: '85%',
    twelfthFile: { name: 'rohan_12th.jpg', size: 1100000, type: 'image/jpeg' },
    ugFile: null,
    jeeScore: '', neetScore: '', cetScore: '',
    preferredProgram: 'B.Tech', preferredCity: 'Kerala',
    preferredUniversity: 'Rajagiri School of Engineering & Technology',
    goals: 'Mechanical engineering, ideally with an automotive specialization later. Want to stay in Kerala for undergrad.',
  },
  {
    id: 'FL-C9L4N6', submittedAt: '2026-05-21T16:48:00Z', status: 'Documents verified', studyLevel: 'UG',
    fullName: 'Saanvi Patel', email: 'saanvi.p@example.com', phone: '+91 98765 43210',
    dob: '2006-11-22', city: 'Mangalore', state: 'Karnataka',
    tenthBoard: 'State Board', tenthYear: '2022', tenthPct: '88%',
    tenthFile: { name: 'saanvi_10th.pdf', size: 290000, type: 'application/pdf' },
    eleventhStream: 'Science (PCB)', eleventhSchool: '',
    eleventhFile: null,
    twelfthBoard: 'State Board', twelfthYear: '2024', twelfthPct: '82%',
    twelfthFile: { name: 'saanvi_12th.pdf', size: 310000, type: 'application/pdf' },
    ugFile: null,
    jeeScore: '', neetScore: '512 / 720', cetScore: '',
    preferredProgram: 'B.Sc Nursing', preferredCity: 'Mangalore',
    preferredUniversity: 'A.J. Institute of Medical Sciences & Research Centre',
    goals: 'Want to specialize in pediatric nursing eventually. Looking for a college with good clinical exposure.',
  },
  {
    id: 'FL-D2H5Q3', submittedAt: '2026-05-21T11:02:00Z', status: 'Lead', studyLevel: 'UG',
    fullName: 'Karthik Subramanian', email: 'karthik.s@example.com', phone: '+91 90030 12121',
    dob: '2007-06-19', city: 'Coimbatore', state: 'Tamil Nadu',
    tenthBoard: 'State Board', tenthYear: '2023', tenthPct: '93%',
    tenthFile: { name: 'karthik_10th.pdf', size: 420000, type: 'application/pdf' },
    eleventhStream: 'Science (PCM)', eleventhSchool: 'PSG Public Schools',
    eleventhFile: { name: 'karthik_11th.pdf', size: 260000, type: 'application/pdf' },
    twelfthBoard: 'State Board', twelfthYear: '2025', twelfthPct: '90%',
    twelfthFile: { name: 'karthik_12th.pdf', size: 350000, type: 'application/pdf' },
    ugFile: null,
    jeeScore: '94.8 percentile', neetScore: '', cetScore: '',
    preferredProgram: 'B.Tech', preferredCity: 'Coimbatore',
    preferredUniversity: 'PSG Institutions',
    goals: 'ECE specialization. Family is in Coimbatore, want to stay close.',
  },
  {
    id: 'FL-E7J1R8', submittedAt: '2026-05-20T14:33:00Z', status: 'Admitted', studyLevel: 'UG',
    fullName: 'Mehek Iyer', email: 'mehek.iyer@example.com', phone: '+91 99007 65432',
    dob: '2006-09-08', city: 'Bangalore', state: 'Karnataka',
    tenthBoard: 'CBSE', tenthYear: '2022', tenthPct: '96%',
    tenthFile: { name: 'mehek_10th.pdf', size: 450000, type: 'application/pdf' },
    eleventhStream: 'Humanities / Arts', eleventhSchool: 'Christ Junior College',
    eleventhFile: { name: 'mehek_11th.pdf', size: 290000, type: 'application/pdf' },
    twelfthBoard: 'CBSE', twelfthYear: '2024', twelfthPct: '94%',
    twelfthFile: { name: 'mehek_12th.pdf', size: 380000, type: 'application/pdf' },
    ugFile: null,
    jeeScore: '', neetScore: '', cetScore: '',
    preferredProgram: 'Degree', preferredCity: 'Bangalore',
    preferredUniversity: "St. Joseph's University",
    goals: "Psychology major, possibly minor in literature. Interested in clinical practice after a master's.",
  },
  {
    id: 'FL-F4G8T2', submittedAt: '2026-05-19T09:17:00Z', status: 'Contacted', studyLevel: 'UG',
    fullName: 'Devansh Rao', email: 'devansh.rao@example.com', phone: '+91 99887 11223',
    dob: '2007-04-25', city: 'Chennai', state: 'Tamil Nadu',
    tenthBoard: 'CBSE', tenthYear: '2023', tenthPct: '85%',
    tenthFile: { name: 'devansh_10th.jpg', size: 980000, type: 'image/jpeg' },
    eleventhStream: 'Science (PCMB)', eleventhSchool: 'Velammal Bodhi Campus',
    eleventhFile: null,
    twelfthBoard: 'Not yet completed', twelfthYear: '', twelfthPct: '',
    twelfthFile: null,
    ugFile: null,
    jeeScore: '', neetScore: '', cetScore: '',
    preferredProgram: 'MBBS', preferredCity: 'Chennai',
    preferredUniversity: 'Chettinad Academy of Research and Education',
    goals: 'Goal: MBBS. Working hard on NEET 2026 prep right now.',
  },
];
